_BASE_: "../OWOD-FPN.yaml"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  STEPS: []
  MAX_ITER: 20000
  WARMUP_ITERS: 500
DATASETS:
  TRAIN: ('t2_voc_coco_2007_ft',)
  TEST: ("voc_coco_2007_test_2",)
OUTPUT_DIR: "repeat/t2/ft"
OWOD:
  PREV_INTRODUCED_CLS: 20
  CUR_INTRODUCED_CLS: 20