_BASE_: "../OWOD-FPN.yaml"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  STEPS: []
  MAX_ITER: 10000
OUTPUT_DIR: "repeat/t3/ft"
DATASETS:
  TRAIN: ('t3_voc_coco_2007_ft',)
  TEST: ("voc_coco_2007_test_3",)
OWOD:
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20