_BASE_: "../OWOD-FPN.yaml"
DATASETS:
  TRAIN: ('t3_voc_coco_2007_train', ) 
  TEST: ('voc_coco_2007_test_3', )
SOLVER:
  BASE_LR: 0.001
  STEPS: ()
  MAX_ITER: 80000
  WARMUP_ITERS: 500
OUTPUT_DIR: "repeat/t3"
OWOD:
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20